mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: springboot_crud.demo.beans
  #executor-type: batch

spring:
  datasource:
    url: jdbc:mysql:///ssm
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
